export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SET_USER = "SET_USER";
export const LOAD_IMAGES_START = "LOAD_IMAGES_START";
export const LOAD_IMAGES_FAIL = "LOAD_IMAGES_FAIL";
export const LOAD_IMAGES_SUCCESS = "LOAD_IMAGES_SUCCESS";
export const LOAD_PUBLIC_IMAGES_SUCCESS = "LOAD_PUBLIC_IMAGES_SUCCESS";

export const ERROR = "ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAIL = "UPLOAD_IMAGE_FAIL";

export const MAKE_PUBLIC_START = "MAKE_PUBLIC_START";
export const MAKE_PUBLIC_FAIL = "MAKE_PUBLIC_FAIL";
export const MAKE_PUBLIC_SUCCESS = "MAKE_PUBLIC_SUCCESS";

export const UNMAKE_PUBLIC_START = "UNMAKE_PUBLIC_START";
export const UNMAKE_PUBLIC_FAIL = "UNMAKE_PUBLIC_FAIL";
export const UNMAKE_PUBLIC_SUCCESS = "UNMAKE_PUBLIC_SUCCESS";
